version: '3.1'

services:
  postgres:
    image: postgres:13.3-alpine
    restart: always
    ports: 
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.1.1.cli-migrations-v3
    ports:
      - "127.0.0.1:9999:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ../svc-hasura/metadata:/hasura-metadata
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
