version: '3.9'

services:
  postgres:
    image: postgres:14.5-alpine
    restart: on-failure
    ports: 
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../svc-server:/app

  hasura:
    image: hasura/graphql-engine:v2.10.0.cli-migrations-v3
    ports:
      - "127.0.0.1:9999:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    volumes:
      - ../svc-hasura/metadata:/hasura-metadata
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
