version: '3.1'

services:
  postgres:
    image: postgres:13.3-alpine
    restart: always
    ports: 
      - "127.0.0.1:5432:5432"
    env_file:
      - env_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  kc:
    image: stayradiated/kc:latest
    ports:
      - "127.0.0.1:7947:7947"
      - "127.0.0.1:7949:7949"
      - "127.0.0.1:7950:7950"
    restart: always
    env_file: 
      - env_kc
    depends_on:
      - postgres
    volumes:
      - ./fullchain.pem:/ssl_certificate.crt
      - ./privkey.pem:/ssl_certificate_key.key

volumes:
  pgdata:
