version: '3.9'

services:
  postgres:
    image: postgres:14.5-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - env_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    image: caddy:2.5.2
    restart: unless-stopped
    ports:
      - "5555:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - hasura
      - server

  web:
    restart: unless-stopped
    image: stayradiated/volatile:web-latest
    env_file:
      - env_web
    depends_on:
      - hasura

  hasura:
    restart: unless-stopped
    image: stayradiated/volatile:hasura-latest
    env_file:
      - env_hasura
    depends_on:
      - postgres
      - server

  server:
    restart: unless-stopped
    image: stayradiated/volatile:server-latest
    env_file:
      - env_server
    depends_on:
      - postgres

volumes:
  pgdata:
  caddy_data:
  caddy_config:
