version: '3.1'

services:
  postgres:
    image: postgres:13.3-alpine
    restart: always
    ports: 
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
